import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

export interface Violation {
  gate: string;
  file: string;
  line?: number;
  message: string;
}

export interface Gate {
  name: string;
  description: string;
  run(root: string): Violation[];
}

/** Top-level folders that hold shipped or shippable code. */
export const CODE_ROOTS = ['apps', 'packages', 'services'];

const SKIP_DIRS = new Set([
  'node_modules',
  '.git',
  '.expo',
  'dist',
  'coverage',
  'target',
  // Generated by `expo prebuild`; checked separately by the permissions gate.
  'android',
  'ios',
]);

const TEXT_EXT = /\.(ts|tsx|js|jsx|mjs|cjs|json|xml|plist|gradle|kt|java|swift|m|mm|rs|toml|yaml|yml)$/;

/** Lists text files under the given roots, relative to `root`, skipping generated and vendored folders. */
export function listFiles(root: string, roots: string[] = CODE_ROOTS): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      if (SKIP_DIRS.has(name)) continue;
      const full = join(dir, name);
      const st = statSync(full);
      if (st.isDirectory()) walk(full);
      else if (TEXT_EXT.test(name)) out.push(relative(root, full).split(sep).join('/'));
    }
  };
  for (const r of roots) {
    const full = join(root, r);
    if (existsSync(full)) walk(full);
  }
  return out.sort();
}

export function read(root: string, file: string): string {
  return readFileSync(join(root, file), 'utf8');
}

/** Returns one violation per line that matches any of the patterns. */
export function scanLines(
  gate: string,
  root: string,
  files: string[],
  patterns: { re: RegExp; message: string }[],
): Violation[] {
  const out: Violation[] = [];
  for (const file of files) {
    const lines = read(root, file).split('\n');
    lines.forEach((text, i) => {
      for (const p of patterns) {
        if (p.re.test(text)) out.push({ gate, file, line: i + 1, message: p.message });
      }
    });
  }
  return out;
}

export interface WorkspacePackage {
  file: string;
  name: string;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
}

/** Every package.json in the repo (root and workspaces), outside node_modules. */
export function listPackages(root: string): WorkspacePackage[] {
  const files = ['package.json', ...listFiles(root, [...CODE_ROOTS, 'tools']).filter((f) => f.endsWith('/package.json'))];
  return files
    .filter((f) => existsSync(join(root, f)))
    .map((file) => {
      const json = JSON.parse(read(root, file)) as Partial<WorkspacePackage>;
      return {
        file,
        name: json.name ?? file,
        dependencies: json.dependencies ?? {},
        devDependencies: json.devDependencies ?? {},
      };
    });
}

/** Package names that appear anywhere in pnpm-lock.yaml, including transitive ones. */
export function lockfilePackages(root: string): Set<string> {
  const file = join(root, 'pnpm-lock.yaml');
  const names = new Set<string>();
  if (!existsSync(file)) return names;
  const text = readFileSync(file, 'utf8');
  // Package entries look like `  '@scope/name@1.2.3':` or `  name@1.2.3(peer@x):`.
  const re = /^ {2}'?((?:@[^/@\s']+\/)?[^@\s'/][^@\s']*)@[^\s']+'?:\s*$/gm;
  for (const m of text.matchAll(re)) if (m[1]) names.add(m[1]);
  return names;
}
