import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { type Gate, read, type Violation } from './lib.js';

/**
 * PRD 7.2 permission matrix; CLAUDE.md invariant 11.
 *
 * This gate checks the native projects generated by `expo prebuild`. Permissions that native
 * libraries add through manifest merging only appear in the merged manifest of a Gradle build;
 * the release pipeline must run the same check against that merged manifest (PRD 7.2: "checked
 * against the built Android manifest"). The `tools:node="remove"` entries required below make
 * the merge drop location and advertising permissions even if a library declares them.
 */
export const MOBILE_DIR = 'apps/mobile';
export const ANDROID_MANIFEST = `${MOBILE_DIR}/android/app/src/main/AndroidManifest.xml`;

export const ANDROID_ALLOWED = new Set([
  'android.permission.INTERNET',
  'android.permission.CAMERA', // only requested when the in-app camera opens
  'android.permission.RECORD_AUDIO', // only requested when recording
]);

/** Must be present with tools:node="remove", so no library can merge them back in. */
export const ANDROID_REQUIRED_REMOVALS = [
  'com.google.android.gms.permission.AD_ID',
  'android.permission.ACCESS_FINE_LOCATION',
  'android.permission.ACCESS_COARSE_LOCATION',
  'android.permission.ACCESS_BACKGROUND_LOCATION',
  'android.permission.READ_EXTERNAL_STORAGE',
  'android.permission.WRITE_EXTERNAL_STORAGE',
  'android.permission.READ_PHONE_STATE',
  'android.permission.POST_NOTIFICATIONS',
  // expo-secure-store merges these in; found by the merged-manifest check on the first real build.
  'android.permission.USE_BIOMETRIC',
  'android.permission.USE_FINGERPRINT',
];

/** iOS usage-description keys allowed by the matrix. Any other NS…UsageDescription fails. */
export const IOS_ALLOWED_USAGE_KEYS = new Set([
  'NSCameraUsageDescription',
  'NSMicrophoneUsageDescription',
  'NSPhotoLibraryUsageDescription', // limited picker only
]);

interface ManifestPermission {
  name: string;
  removed: boolean;
  line: number;
}

export function parseAndroidPermissions(xml: string): ManifestPermission[] {
  const out: ManifestPermission[] = [];
  const re = /<uses-permission(?:-sdk-23)?\b([^>]*)\/?>/g;
  for (const m of xml.matchAll(re)) {
    const attrs = m[1] ?? '';
    const name = /android:name="([^"]+)"/.exec(attrs)?.[1];
    if (!name) continue;
    out.push({
      name,
      removed: /tools:node="remove"/.test(attrs),
      line: xml.slice(0, m.index).split('\n').length,
    });
  }
  return out;
}

export function parsePlistKeys(xml: string): { key: string; line: number }[] {
  const out: { key: string; line: number }[] = [];
  for (const m of xml.matchAll(/<key>([^<]+)<\/key>/g)) {
    out.push({ key: m[1] ?? '', line: xml.slice(0, m.index).split('\n').length });
  }
  return out;
}

export function findInfoPlist(root: string): string | undefined {
  const iosDir = join(root, MOBILE_DIR, 'ios');
  if (!existsSync(iosDir)) return undefined;
  for (const name of readdirSync(iosDir)) {
    const candidate = `${MOBILE_DIR}/ios/${name}/Info.plist`;
    if (existsSync(join(root, candidate))) return candidate;
  }
  return undefined;
}

export const permissions: Gate = {
  name: 'permissions',
  description: 'Generated Android manifest and iOS Info.plist match the PRD 7.2 permission matrix (invariant 11)',
  run(root) {
    const out: Violation[] = [];
    const merged = process.env.FACTO_MERGED_MANIFEST;
    if (merged) {
      if (!existsSync(merged)) return [{ gate: this.name, file: merged, message: 'FACTO_MERGED_MANIFEST points to a missing file' }];
      return checkMergedManifest(readFileSync(merged, 'utf8'), merged);
    }
    if (!existsSync(join(root, MOBILE_DIR))) return out; // no app yet
    const v = (file: string, message: string, line?: number) => out.push({ gate: this.name, file, line, message });

    if (!existsSync(join(root, ANDROID_MANIFEST))) {
      v(ANDROID_MANIFEST, 'missing: run `pnpm --filter @facto/mobile prebuild` before the gates');
    } else {
      const perms = parseAndroidPermissions(read(root, ANDROID_MANIFEST));
      for (const p of perms) {
        if (!p.removed && !ANDROID_ALLOWED.has(p.name)) v(ANDROID_MANIFEST, `permission not in the PRD 7.2 matrix: ${p.name}`, p.line);
      }
      for (const name of ANDROID_REQUIRED_REMOVALS) {
        if (!perms.some((p) => p.name === name && p.removed)) v(ANDROID_MANIFEST, `${name} must be explicitly removed (tools:node="remove")`);
      }
    }

    const plist = findInfoPlist(root);
    if (!plist) {
      v(`${MOBILE_DIR}/ios/*/Info.plist`, 'missing: run `pnpm --filter @facto/mobile prebuild` before the gates');
    } else {
      const text = read(root, plist);
      for (const { key, line } of parsePlistKeys(text)) {
        if (/^NS\w*UsageDescription$/.test(key) && !IOS_ALLOWED_USAGE_KEYS.has(key)) v(plist, `usage key not in the PRD 7.2 matrix: ${key}`, line);
        if (key.startsWith('NSLocation')) v(plist, `location key: ${key}`, line);
        if (key === 'UIBackgroundModes') v(plist, 'background modes are not allowed in V1 (no push, no background location)', line);
      }
    }
    return out;
  },
};

/**
 * Merged-manifest mode (CI emulator job): set FACTO_MERGED_MANIFEST to the Gradle-merged
 * AndroidManifest.xml. Removed permissions are gone from a merged manifest, so here the rule is
 * simply: every declared permission is in the matrix. The one extra allowed entry is the
 * app-private `<package>.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION` that androidx.core declares
 * for the app's own broadcast receivers; it grants nothing outside the app.
 */
export function checkMergedManifest(xml: string, file: string): Violation[] {
  const pkg = /<manifest[^>]*\spackage="([^"]+)"/.exec(xml)?.[1];
  const own = pkg ? `${pkg}.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION` : null;
  const out: Violation[] = [];
  for (const p of parseAndroidPermissions(xml)) {
    if (p.removed) continue;
    if (ANDROID_ALLOWED.has(p.name) || p.name === own) continue;
    out.push({ gate: 'permissions', file, line: p.line, message: `merged manifest declares a permission outside the PRD 7.2 matrix: ${p.name}` });
  }
  return out;
}
